"""Advanced statevector visualisations using Qiskit."""
import numpy as np
from qiskit.visualization import plot_bloch_multivector, plot_state_city, plot_state_qsphere
import matplotlib.pyplot as plt
from qiskit import QuantumCircuit
from qiskit_aer import AerSimulator
from qiskit.exceptions import QiskitError
from typing import Union

def get_statevector(circuit: QuantumCircuit) -> np.ndarray:
    """Return statevector of a given circuit."""
    if not isinstance(circuit, QuantumCircuit):
        raise TypeError("Input must be a QuantumCircuit object.")
    if circuit.num_qubits > 10: # Limit for practical statevector simulation
        raise ValueError(f"Circuit has too many qubits ({circuit.num_qubits}) for statevector simulation. Max 10 recommended.")

    sim = AerSimulator()
    try:
        # Ensure the circuit has no measurements if we want a statevector
        qc_copy = circuit.remove_final_measurements(inplace=False)
        qc_copy.save_statevector()
        result = sim.run(qc_copy, shots=1).result()
        return result.get_statevector()
    except QiskitError as e:
        raise RuntimeError(f"Qiskit error during statevector simulation: {e}")
    except Exception as e:
        raise RuntimeError(f"An unexpected error occurred during statevector simulation: {e}")

def plot_circuit_state(circuit: QuantumCircuit, title: str = "") -> plt.Figure:
    """Plot Bloch sphere, city, and qsphere for a circuit."""
    if not isinstance(circuit, QuantumCircuit):
        raise TypeError("Input must be a QuantumCircuit object.")
    if circuit.num_qubits > 3: # Bloch sphere is good for 1 qubit, city/qsphere for a few.
        print(f"Warning: Visualizations may be complex for {circuit.num_qubits} qubits. Recommended max 3.")

    state = get_statevector(circuit)
    
    # Create a figure and a grid of subplots
    fig, axes = plt.subplots(1, 3, figsize=(18, 6)) # Increased figure size for better visibility
    fig.suptitle(title, fontsize=16)

    # Bloch sphere (only works well for 1 qubit)
    if circuit.num_qubits == 1:
        try:
            bloch_fig = plot_bloch_multivector(state)
            # plot_bloch_multivector returns a matplotlib Figure object directly
            # We need to get its axes and transfer to our subplot
            bloch_axes = bloch_fig.get_axes()[0]
            axes[0].set_title("Bloch Sphere")
            # Copy elements from bloch_fig to axes[0]
            for child in bloch_axes.get_children():
                axes[0].add_artist(child)
            axes[0].set_xlim(bloch_axes.get_xlim())
            axes[0].set_ylim(bloch_axes.get_ylim())
            axes[0].set_zlim(bloch_axes.get_zlim())
            axes[0].set_aspect("auto")
            plt.close(bloch_fig) # Close the extra figure generated by plot_bloch_multivector
        except Exception as e:
            axes[0].text(0.5, 0.5, f"Error plotting Bloch: {e}", horizontalalignment=\'center\', verticalalignment=\'center\', transform=axes[0].transAxes)
            axes[0].set_title("Bloch Sphere (Error)")
    else:
        axes[0].text(0.5, 0.5, "Bloch sphere for 1 qubit only", horizontalalignment=\'center\', verticalalignment=\'center\', transform=axes[0].transAxes)
        axes[0].set_title("Bloch Sphere")

    # City plot
    try:
        city_fig = plot_state_city(state)
        city_axes = city_fig.get_axes()[0]
        axes[1].set_title("City Plot")
        for child in city_axes.get_children():
            axes[1].add_artist(child)
        axes[1].set_xlim(city_axes.get_xlim())
        axes[1].set_ylim(city_axes.get_ylim())
        axes[1].set_zlim(city_axes.get_zlim())
        axes[1].set_aspect("auto")
        plt.close(city_fig)
    except Exception as e:
        axes[1].text(0.5, 0.5, f"Error plotting City: {e}", horizontalalignment=\'center\', verticalalignment=\'center\', transform=axes[1].transAxes)
        axes[1].set_title("City Plot (Error)")

    # Qsphere
    try:
        qsphere_fig = plot_state_qsphere(state)
        qsphere_axes = qsphere_fig.get_axes()[0]
        axes[2].set_title("Q-Sphere")
        for child in qsphere_axes.get_children():
            axes[2].add_artist(child)
        axes[2].set_xlim(qsphere_axes.get_xlim())
        axes[2].set_ylim(qsphere_axes.get_ylim())
        axes[2].set_zlim(qsphere_axes.get_zlim())
        axes[2].set_aspect("auto")
        plt.close(qsphere_fig)
    except Exception as e:
        axes[2].text(0.5, 0.5, f"Error plotting Q-Sphere: {e}", horizontalalignment=\'center\', verticalalignment=\'center\', transform=axes[2].transAxes)
        axes[2].set_title("Q-Sphere (Error)")

    plt.tight_layout(rect=[0, 0.03, 1, 0.95]) # Adjust layout to prevent title overlap
    return fig

def visualise_bb84_step(bit: int, basis: str) -> plt.Figure:
    """
    Prepare a single qubit as per BB84 and visualise.
    Returns a matplotlib Figure object.
    """
    if bit not in [0, 1]:
        raise ValueError("Bit must be 0 or 1.")
    if basis not in ["Z", "X"]:
        raise ValueError("Basis must be \'Z\' or \'X\'.")

    qc = QuantumCircuit(1)
    if bit == 1:
        qc.x(0)
    if basis == "X":
        qc.h(0)
    
    return plot_circuit_state(qc, f"Alice prepares bit={bit}, basis={basis}")
